note collection script into myenv

diff --git a/.myenv/env_func_bash b/.myenv/env_func_bash
--- a/.myenv/env_func_bash
+++ b/.myenv/env_func_bash
@@ -82,6 +82,11 @@ function func_bak_file {
 	[ -w "$(dirname ${1})" ] && cp "$1" $target || sudo cp "$1" $target 
 }
 
+function func_tag_value_raw {
+	tags=$MY_ENV_LIST/tags
+	sed -n -e "s+^${1}=++p" $tags
+}
+
 function func_tag_value {
 	#desc="Desc: translate a tag value, or return itself if not a tag"
 	#usage="Usage: $FUNCNAME [filename]"
@@ -96,27 +101,22 @@ function func_tag_value {
 	# NO translation, contain no-tag char
 	[ $(echo "$*" | grep -c "/\| ") -ge 1 ] && echo $* && return 0
 
-	# check tag
-	tags=$MY_ENV_LIST/tags
-	tag_value=`sed -n -e "s/^${1}=//p" $tags`
+	tag_value_raw="$(func_tag_value_raw ${1})"
 
 	# not a tag, return itself
-	[ -z "$tag_value" ] && echo $1 && return 0
+	[ -z "$tag_value_raw" ] && echo $1 && return 0
 
 	# eval
-	func_tag_eval $tag_value
+	func_eval $tag_value_raw
 }
 
-function func_tag_eval {
+function func_eval {
 	func_param_check 1 "USAGE: $FUNCNAME <tag>" "$@"
 
 	tag=$*
 
 	# eval value if contains var or cmd substitution, otherwise return itself
 	if [ $(echo $tag | grep -c '`\|$') -ge 1 ] ; then
-		# remove starting and trailing quotes, otherwise eval will fail
-		#tag=`echo $tag | sed -e "s/^['\"]//;s/['\"]$//"`		
-
 		eval echo $tag
 	else
 		echo $tag
@@ -177,10 +177,12 @@ function func_find_type_cache {
 
 	if [ "$find_type" = "d" ] ; then
 		list_file=".dl_me.txt" 
-		func_gen_list d $base $list_file || return 1
+		#func_gen_list d $base $list_file || return 1
+		func_gen_filedirlist $base $base/$list_file -type d || return 1
 	else
 		list_file=".fl_me.txt"
-		func_gen_list f $base $list_file || return 1
+		#func_gen_list f $base $list_file || return 1
+		func_gen_filedirlist $base $base/$list_file -type f || return 1
 	fi
 
 	search=`echo "$*" | sed -e '/^$/q;s/ \|^/.*\/.*/g;s/\$/[^\/]*/'`
@@ -340,7 +342,7 @@ function func_ls {
 	# Translate tag
 	base="./"
 	if [[ -n "`func_tag_text_value $1`" ]] ;then 
-		base="`func_tag_eval_value $1`/"
+		base="`func_tag_value $1`/"
 		shift
 	fi
 	pathPattern=`echo "$*" | sed -e '/^$/q;s/ /*\//g;s/$/*/'`
@@ -364,10 +366,41 @@ function func_head_cmd {
 	func_head $show_lines "$cmd_result"
 }
 
-function func_gen_list {
+function func_gen_filedirlist {
 	# TODO: make a conversion of $type+l_me.txt ?
 	#[ "`realpath $base`" = "`realpath $HOME`" ] && echo yes || echo no
-	func_param_check 3 "Usage: $FUNCNAME [find_type (f,file;d,dir)] [base] [fl_name]" "$@"
+	func_param_check 3 "Usage: $FUNCNAME [base] [listfile] [find_options]" "$@"
+
+	base=$1
+	listfile=$2
+	shift;shift
+	find_options="$*"
+
+	# for better compatibility, always: 1) use relative path (./) or path start with variable
+	tag_value_raw="$(func_tag_value_raw ${base})"
+	if [ -n "$tag_value_raw" ]; then
+		base=$(func_eval $tag_value_raw)
+		base_raw=$tag_value_raw
+	else
+		base=$base
+		base_raw="."
+	fi
+
+	[ -e "$listfile" ] && return 0
+	[ ! -e "$base" ] && echo "ERROR: $base not exist" && return 1
+	[ ! -w "$(dirname $listfile)" ] && echo "ERROR: $(dirname $listfile) not exist or not writable" && return 1
+
+	echo "$listfile not exist, create it..." 1>&2
+	\cd $base &> /dev/null
+	[ -w ./ ] && find -L ./ $find_options | sed -e "s+^./+${base_raw}/+" > $listfile || echo "ERROR: no write permisson for $PWD!"
+	\cd - &> /dev/null
+}
+
+function func_gen_list {
+	# Deprecated: use func_tag_value_raw !
+	# TODO: make a conversion of $type+l_me.txt ?
+	#[ "`realpath $base`" = "`realpath $HOME`" ] && echo yes || echo no
+	func_param_check 3 "Usage: $FUNCNAME [find_type (f,file;d,dir)] [base] [listfile]" "$@"
 
 	find_type=$1
 	base=$2
@@ -415,12 +448,58 @@ function func_gen_list_f_me {
 	done
 }
 
+function func_gen_collection_note {
+	target_base=$MY_ENV/zgen/collection_note
+	target_original_file=$target_base/original_files
+	target_note_collection_fl=$target_base/note_collection_fl.txt
+	target_note_collection_txt=$target_base/note_collection_txt.txt
+	source_base=(dcd dco dcc dcb   me   ecb ece ech ecs ecz)	# Not included DCM, put DCD first
+	source_note_list=$MY_ENV/list/collection_quick_link_files
+
+	# clean up old things
+	[ -e "$target_base" ] && rm -rf "$target_base"
+
+	# init target dir, gen file lists
+	func_mkdir_cd "$target_base"
+	for tag in ${source_base[@]}
+	do
+		func_gen_filedirlist $tag $target_base/fl_${tag}.txt -type f
+	done
+
+	# create filelist to collect
+	sed -e "/\.lnk$/d" fl_*.txt | grep -i "\(A_NOTE\|--NOTE--\|\.bat$\|\.sh$\)" >> ${target_note_collection_fl}
+
+	# bak orginal file and collect notes
+	mkdir $target_original_file
+	sed -e "" "$source_note_list" >> ${target_note_collection_txt}
+	echo ">>> This line is to ensure this file can not be excuted successfully" >> $target_note_collection_txt
+	while read line
+	do
+		source_path="$(func_eval "$line")"
+		[ -d "$source_path" ] && echo -e "INFO: skipping dir: $line" && continue
+
+		# backup original files, need udpate file name to avoid name confliction
+		target_file=$(echo "$line" | sed -e 's+/\|:+@+g;s+\$\| \|\(\|\)\|（\|）\|&++g')
+		cp "$source_path" "$target_original_file/$target_file" 
+
+		# collect text files
+		if [ -z "${line##*.txt}" ] ; then 
+			echo -e "\n\n>>> $line\n\n"	>> ${target_note_collection_txt}
+			sed -e "s///" "$source_path"	>> ${target_note_collection_txt}
+			#cat "$source_path"	>> ${target_note_collection_txt}
+		fi
+	done < ${target_note_collection_fl}
+
+	# backup collection
+	func_backup_dated "$target_original_file" && rm -rf "$target_original_file"
+}
+
 function func_grep_cmd {
 	func_param_check 2 "Usage: $FUNCNAME <search_str> <cmd>" "$@"
 
 	search_str=$1
 	shift
-	eval "$@" | grep "$search_str"
+	eval "$@" | grep -i "$search_str"
 }
 
 function func_grep_dir_cached {
@@ -437,7 +516,9 @@ function func_grep_dir_cached {
 	filelist=.fl_me.txt
 	grep_result=.grep_me.txt
 
-	func_gen_list f $base $filelist || func_die "ERROR: failed to gen $base/$filelist"
+	#func_gen_list f $base $filelist || func_die "ERROR: failed to gen $base/$filelist"
+	func_gen_filedirlist $base $base/$filelist -type f || func_die "ERROR: failed to gen $base/$filelist"
+
 
 	# Get search string and options
 		# Case need handle
@@ -979,7 +1060,7 @@ function func_backup_listed {
 		# TODO duplicated code block - start - evalfl1
 		sed -e "/^\s*$/d;/^\s*#/d;" $fl | while read line; do
 			# eval path, check empty value
-			[ -n "$line" ] && candidate=`func_tag_eval $line` || continue
+			[ -n "$line" ] && candidate=`func_eval $line` || continue
 			[ -z "$candidate" ] && echo -e "WARN: candiate is empty: $line !" && continue
 
 			# Try $HOME as base (myenv backup need this for git listed files)
