update unison config and improve functions

diff --git a/.myenv/env_func_bash b/.myenv/env_func_bash
--- a/.myenv/env_func_bash
+++ b/.myenv/env_func_bash
@@ -1,13 +1,5 @@
 #!/bin/bash
 
-#function func_tag_text_value {
-#	usage="Usage: func_tag_text_value [tag]"
-#	[[ -z $1 ]] && echo $usage && return 1
-#
-#	tags=$MY_ENV_LIST/tags
-#	sed -n -e "s/${1}=//p" $tags
-#}
-
 function func_tag_value {
 	# DESC: translate a tag value, or return itself if not a tag
 
@@ -53,9 +45,49 @@ function func_select_line {
 	eval $result_var_name=$user_selection
 }
 
+function func_find_type_cache {
+	# NOTE: must keep interface consistency with func_find_type
+	usage="Usage: func_find_type_cache [find_type (f,file;d,dir)] [base] [pattern]"
+	[ $# -lt 3 ] && echo $usage && return 1
+
+	find_type=$1
+	base=$2
+	shift;shift
+
+	if [ "$find_type" = "d" ] ; then
+		list_file=".dl_me.txt" 
+		func_gen_list d $base $list_file
+	else
+		list_file=".fl_me.txt"
+		func_gen_list f $base $list_file
+	fi
+
+	search=`echo "$*" | sed -e '/^$/q;s/ \|^/.*\/.*/g;s/\$/[^\/]*/'`
+	targets=`cat $base/$list_file | sed -e "/^$/d" | grep "$search"`
+
+	echo "$targets"
+}
+
+function func_find_type {
+	# NOTE: must keep interface consistency with func_find_type_cache
+	usage="Usage: func_find_type [find_type (f,file;d,dir)] [base] [pattern]"
+	[ $# -lt 3 ] && echo $usage && return 1
+
+	find_type=$1
+	base=$2
+	shift;shift
+
+	search=`echo "$*" | sed -e '/^$/q;s/ \|^/.*\/.*/g;s/\$/[^\/]*/'`
+	targets=`find -P "$base" -iregex "$search" -xtype $find_type | sed -e "/^$/d"`				# 1st try, not follow links
+	[ -z "$targets" ] && targets=`find -L "$base" -iregex "$search" -type $find_type | sed -e "/^$/d"`	# not found, follow links maybe works
+	[ -z "$targets" ] && return 1										# not found, return
+
+	echo "$targets"
+}
+
 function func_find_cache {
 	# NOTE: must keep interface consistency with func_find
-	usage="Usage: func_find [result_var_name] [find_type] [base] [pattern]"
+	usage="Usage: func_find [result_var_name] [find_type (f,file;d,dir)] [base] [pattern]"
 	[ $# -lt 4 ] && echo $usage && return 1
 
 	# need use variable to "return" result
@@ -71,7 +103,7 @@ function func_find_cache {
 
 function func_find {
 	# NOTE: must keep interface consistency with func_find_cache
-	usage="Usage: func_find [result_var_name] [find_type] [base] [pattern]"
+	usage="Usage: func_find [result_var_name] [find_type (f,file;d,dir)] [base] [pattern]"
 	[ $# -lt 4 ] && echo $usage && return 1
 
 	# need use variable to "return" result
@@ -82,93 +114,6 @@ function func_find {
 
 	targets=`func_find_type $find_type $*`
 	func_select_line $result_var_name "$targets"
-}
-
-function func_find_type_cache {
-	# NOTE: must keep interface consistency with func_find_type
-	usage="Usage: func_find_type_cache [find_type] [base] [pattern]"
-	[ $# -lt 3 ] && echo $usage && return 1
-
-	find_type=$1
-	base=$2
-	shift;shift
-
-	if [ "$find_type" = "d" ] ; then
-		list_file=".dl_me.txt" 
-		func_gen_dirlist $base $list_file
-	else
-		list_file=".fl_me.txt"
-		func_gen_filelist $base $list_file
-	fi
-
-	search=`echo "$*" | sed -e '/^$/q;s/ \|^/.*\/.*/g;s/\$/[^\/]*/'`
-	targets=`cat $base/$list_file | sed -e "/^$/d" | grep "$search"`
-
-	echo "$targets"
-}
-
-function func_find_type {
-	# NOTE: must keep interface consistency with func_find_type_cache
-	usage="Usage: func_find_type [find_type] [base] [pattern]"
-	[ $# -lt 3 ] && echo $usage && return 1
-
-	find_type=$1
-	base=$2
-	shift;shift
-
-	search=`echo "$*" | sed -e '/^$/q;s/ \|^/.*\/.*/g;s/\$/[^\/]*/'`
-	targets=`find -P "$base" -iregex "$search" -xtype $find_type | sed -e "/^$/d"`				# 1st try, not follow links
-	[ -z "$targets" ] && targets=`find -L "$base" -iregex "$search" -type $find_type | sed -e "/^$/d"`	# not found, follow links maybe works
-	[ -z "$targets" ] && return 1										# not found, return
-
-	echo "$targets"
-}
-
-#function func_cd {
-#	[ -z "$*" ] && \cd && return 0
-#
-#	base="$1"
-#	base_eval="`func_tag_value $1`"
-#	[ -n "${base_eval}" ] && base=${base_eval}
-#	shift
-#	[ -z "$*" ] && func_cd_conditional $base && return 0
-#
-#	#func_find result_target d $base $*			# (2013-05-23) works, non cache version	
-#	func_find_cache result_target d $base $*
-#	[ -d $result_target ] && func_cd_conditional $result_target || func_cd_conditional `dirname $result_target`
-#}
-
-function func_vi {
-	# shortcut - open a new one
-	[ -z "$*" ] && func_vi_conditional && return 0
-
-	# shortcut - only one parameter, and exist
-	tag_eval="`func_tag_value $1`"
-	[ $# -eq 1 ] && func_vi_conditional "$tag_eval" && return 0
-
-	# otherwise need search
-	[ "$tag_eval" != "$1" ] && base="$tag_eval" && shift || base="./"
-
-	#func_find result_target f $base $*			# (2013-05-23) works, non cache version	
-	func_find_cache result_target f $base $*
-	func_vi_conditional "$base/$result_target"
-}
-
-function func_cd {
-	# shortcut - home
-	[ -z "$*" ] && func_cd_conditional && return 0
-
-	# shortcut - only one parameter, and exist
-	tag_eval="`func_tag_value $1`"
-	[ $# -eq 1 ] && [ -d $tag_eval ] && func_cd_conditional $tag_eval && return 0
-
-	# otherwise need search
-	[ "$tag_eval" != "$1" ] && base="$tag_eval" && shift || base="./"
-
-	#func_find result_target d $base $*			# (2013-05-23) works, non cache version	
-	func_find_cache result_target d $base $*
-	[ ! -e $base/$result_target ] && echo "ERROR: $base/$result_target not exist! pls check"
-	[ -d $base/$result_target ] && func_cd_conditional $base/$result_target || func_cd_conditional `dirname $base/$result_target`
 }
 
 function func_vi_conditional {
@@ -204,6 +149,68 @@ function func_cd_conditional {
 	func_head_cmd 10 ll
 }
 
+function func_vi {
+	# shortcut - open a new one
+	[ -z "$*" ] && func_vi_conditional && return 0
+
+	# shortcut - only one parameter, and exist
+	tag_eval="`func_tag_value $1`"
+	[ $# -eq 1 ] && func_vi_conditional "$tag_eval" && return 0
+
+	# otherwise need search
+	[ "$tag_eval" != "$1" ] && base="$tag_eval" && shift || base="./"
+
+	#func_find result_target f $base $*			# (2013-05-23) works, non cache version	
+	func_find_cache result_target f $base $*
+	func_vi_conditional "$base/$result_target"
+}
+
+function func_cd {
+	# shortcut - home
+	[ -z "$*" ] && func_cd_conditional && return 0
+
+	# shortcut - only one parameter, and exist
+	tag_eval="`func_tag_value $1`"
+	[ $# -eq 1 ] && [ -d $tag_eval ] && func_cd_conditional $tag_eval && return 0
+
+	# otherwise need search
+	[ "$tag_eval" != "$1" ] && base="$tag_eval" && shift || base="./"
+
+	#func_find result_target d $base $*			# (2013-05-23) works, non cache version	
+	func_find_cache result_target d $base $*
+	[ ! -e $base/$result_target ] && echo "ERROR: $base/$result_target not exist! pls check"
+	[ -d $base/$result_target ] && func_cd_conditional $base/$result_target || func_cd_conditional `dirname $base/$result_target`
+}
+
+function func_ls { 
+	# shortcut - ls current dir
+	[ -z "$*" ] && eval ll && return 0
+
+	# FOR_DEV: w | !source /home/ouyangzhu/.myenv/env_func_bash; func_ls dev
+
+	# TODO: how to distiguish ll/ls/lla etc
+
+	# TODO: Avoid Filename_Expansion
+
+	# TODO: For Cmd History: ls the cmd output dir?
+
+	# Translate tag
+	base="./"
+	if [[ -n "`func_tag_text_value $1`" ]] ;then 
+		base="`func_tag_eval_value $1`/"
+		shift
+	fi
+	pathPattern=`echo "$*" | sed -e '/^$/q;s/ /*\//g;s/$/*/'`
+
+	echo ------------------------------------"$base/$pathPattern"
+	ls -lhtrF --color=auto $base/$pathPattern
+
+	# Tmp Cmd
+	#search=`echo "$*" | sed -e '/^$/q;s/ \|^\|$/.*/g'`
+	#[[ -n $search ]] && search="-iregex $search"
+	#find $base $search 
+}
+
 function func_cd_tmp_today { 
 	# so could evaluate the date every time
 	func_mkdir_cd $MY_TMP/`date "+%Y-%m-%d"`	
@@ -220,46 +227,27 @@ function func_head_cmd {
 	func_head $show_lines "$cmd_result"
 }
 
-function func_gen_filelist {
-	# TODO: if possible to identify the dir (suffix /)
-	# TODO: check if has write permintion before gen?
+function func_gen_list {
+	# TODO: make a conversion of $type+l_me.txt ?
 	# TODO: if path is home or above, should not gen filelist?
 	#[ "`realpath $base`" = "`realpath $HOME`" ] && echo yes || echo no
 
-	# NOTE: must keep interface consistency with func_gen_dirlist
-	# DESC: only gen file list
-	usage="Usage: func_gen_filelist [base] [fl_name]"
-	[ $# -lt 2 ] && echo $usage && return 1
+	usage="Usage: func_gen_list [find_type (f,file;d,dir)] [base] [fl_name]"
+	[ $# -lt 3 ] && echo $usage && return 1
 
-	base=$1
-	filelist=$2
-	[ -e $base/$filelist ] && return 0
-
-	# make the path relative to the base, for better compitability
-	echo "$base/$filelist not exist, create it..." 1>&2
-	\cd $base
-	find ./ -type f > $filelist
-	\cd -
-}
-
-function func_gen_dirlist {
-	# NOTE: must keep interface consistency with func_gen_filelist
-	# DESC: only gen dir list
-	usage="Usage: func_gen_dirlist [base] [dl_name]"
-	[ $# -lt 2 ] && echo $usage && return 1
-
-	base=$1
-	dirlist=$2
-	[ -e $base/$dirlist ] && return 0
+	find_type=$1
+	base=$2
+	listfile=$3
+	[ -e $base/$listfile ] && return 0
 
 	# make the path relative to the base, for better compitability
-	echo "$base/$dirlist not exist, create it..." 1>&2
-	\cd $base
-	find -L ./ -type d > $base/$dirlist
-	\cd -
+	echo "$base/$listfile not exist, create it..." 1>&2
+	\cd $base &> /dev/null
+	find -L ./ -type $find_type > $listfile
+	\cd - &> /dev/null
 }
 
-function func_gen_filelist_myenv {
+function func_gen_list_myenv {
 
 	filelist=$MY_ENV/.fl_me.txt
 
@@ -287,7 +275,7 @@ function func_gen_grep_result {
 	filelist=.fl_me.txt
 	grep_result=.grep_me.txt
 
-	func_gen_filelist $base $filelist
+	func_gen_list f $base $filelist
 
 	# we treat path in search text as .
 	search_string="$*"
@@ -321,7 +309,7 @@ function func_gen_grep_result_myenv {
 	usage="Usage: func_gen_grep_result_myenv [search]*"
 	[ $# -lt 1 ] && echo $usage && return 1
 
-	func_gen_filelist_myenv 
+	func_gen_list_myenv 
 	func_gen_grep_result $MY_ENV ALL "$*"
 }
 
@@ -334,35 +322,6 @@ function func_head {
 
 	total_lines=$(echo "$*" | wc -l)
 	echo "$*" | sed -n -e "1,${show_lines}p;${show_lines}s/.*/( ...... WARN: more lines suppressed, $total_lines total ...... )/p"
-}
-
-function func_ls { 
-	# FOR_DEV: w | !source /home/ouyangzhu/.myenv/env_func_bash; func_ls dev
-
-	usage="Usage: func_ls [tag] [path]*"
-	[[ -z $1 ]] && echo $usage && return 1
-
-	# TODO: how to distiguish ll/ls/lla etc
-
-	# TODO: Avoid Filename_Expansion
-
-	# TODO: For Cmd History: ls the cmd output dir?
-
-	# Translate tag
-	base="./"
-	if [[ -n "`func_tag_text_value $1`" ]] ;then 
-		base="`func_tag_eval_value $1`/"
-		shift
-	fi
-	pathPattern=`echo "$*" | sed -e '/^$/q;s/ /*\//g;s/$/*/'`
-
-	echo ------------------------------------"$base/$pathPattern"
-	ls -lhtrF --color=auto $base/$pathPattern
-
-	# Tmp Cmd
-	#search=`echo "$*" | sed -e '/^$/q;s/ \|^\|$/.*/g'`
-	#[[ -n $search ]] && search="-iregex $search"
-	#find $base $search 
 }
 
 function func_ip {
