add functions for building, not finished yet

diff --git a/.myenv/env_func_bash b/.myenv/env_func_bash
--- a/.myenv/env_func_bash
+++ b/.myenv/env_func_bash
@@ -1,5 +1,19 @@
 #!/bin/bash
-#[ ! -e $MY_ENV/env_func_bash ] && echo "ERROR: $MY_ENV/env_func_bash not exist" && exit 1 || source $MY_ENV/env_func_bash
+
+#[ ! -e ~/.myenv/env_func_bash ] && echo "ERROR: ~/.myenv/env_func_bash not exist" && exit 1 || source ~/.myenv/env_func_bash
+
+[ -z "$MY_DOC" ]		&& MY_DOC=$HOME/Documents
+[ -z "$MY_TMP" ]		&& MY_TMP=$HOME/amp
+[ -z "$MY_DEV" ]		&& MY_ENV =$HOME/dev
+[ -z "$MY_ENV" ]		&& MY_ENV =$HOME/.myenv
+[ -z "$RVM_HOME" ]		&& RVM_HOME=$HOME/.rvm
+[ -z "$MY_ENV_ZGEN" ]		&& MY_ENV_ZGEN=$MY_ENV/zgen
+[ -z "$MY_ENV_LIST" ]		&& MY_ENV_LIST=$MY_ENV/list
+[ -z "$PYTHON_HOME" ]		&& PYTHON_HOME=$MY_DEV/python
+[ -z "$MY_CODE_MISC" ]		&& MY_CODE_MISC=$MY_DEV/code_misc
+[ -z "$DOT_CACHE_DL" ]		&& DOT_CACHE_DL=.dl_me.txt
+[ -z "$DOT_CACHE_FL" ]		&& DOT_CACHE_FL=.fl_me.txt
+[ -z "$DOT_CACHE_GREP" ]	&& DOT_CACHE_GREP=.grep_me.txt
 
 function func_date {
 	date "+%Y-%m-%d"
@@ -927,11 +941,11 @@ function func_ssh_with_jump {
 	ip_addr=`getent hosts $1 | sed "s/\s\+.*$//"`
 	[[ -z $ip_addr ]] && ip_addr=$1
 
-	PORT=32200
-	JUMP_MACHINE=dw
+	port=32200
+	jump_machine=dw
 	
 	shift
-	ssh -t $JUMP_MACHINE "ssh -p $PORT $ip_addr $@"
+	ssh -t $jump_machine "ssh -p $port $ip_addr $@"
 
 	# TODO: check the $1, if it is a ip, should not parse as unique_name
 	# TODO: add function for run cmd on multiple host
@@ -957,26 +971,26 @@ function func_scp_with_jump {
 		echo "Downloading ..."
 
 		# download content to jump machine
-		ssh $JUMP_MACHINE "scp -r -P $PORT $source ~/$tmpTransferName"
+		ssh $jump_machine "scp -r -P $port $source ~/$tmpTransferName"
 
 		# create dir and download content to local machine 
 		$targetCmd
 		[[ -d $target ]] && targetFullName=$target/$sourceName
-		scp -r -P $PORT ouyangzhu@$JUMP_MACHINE:~/$tmpTransferName $targetFullName
+		scp -r -P $port ouyangzhu@$jump_machine:~/$tmpTransferName $targetFullName
 	else
 		echo "Uploading ..."
 
 		# upload content to jump machine
-		scp -r -P $PORT $source ouyangzhu@$JUMP_MACHINE:~/$tmpTransferName
+		scp -r -P $port $source ouyangzhu@$jump_machine:~/$tmpTransferName
 
 		# create dir and upload content to target machine in jump machine
-		ssh $JUMP_MACHINE "ssh -p $PORT $targetAddr $targetCmd"
+		ssh $jump_machine "ssh -p $port $targetAddr $targetCmd"
 		# TODO: support rename in target (see above)
-		ssh $JUMP_MACHINE "scp -r -P $PORT ~/$tmpTransferName $target"
+		ssh $jump_machine "scp -r -P $port ~/$tmpTransferName $target"
 	fi
 
 	# delete tmp file in jump machine
-	ssh $JUMP_MACHINE "rm -rf ~/$tmpTransferName"
+	ssh $jump_machine "rm -rf ~/$tmpTransferName"
 
 	# Note: seems using ProxyCommand is a better way (not totally work yet), see ~/.ssh/config for more detail
 
@@ -1330,4 +1344,53 @@ function func_mount_iso {
 
 	#mount -t iso9660 -o ro,loop,noauto /your/texlive2012.iso /mnt
 	sudo mount -t iso9660 -o ro,loop,noauto $2 $1
+}
+ 
+function func_build_prepare_source {
+	func_param_check 3 "Usage: $FUNCNAME <source_base> <local_addr> <remote_addr>" "$@" 
+
+	# remote first
+	[ -n "$3" ] && func_build_prepare_source_remote "$1" "$3" || func_build_prepare_source_local "$1" "$2"
+}
+
+function func_build_prepare_source_remote {
+	func_param_check 2 "Usage: $FUNCNAME <source_base> <remote_addr>" "$@" 
+
+	case "$*" in
+		*/hg/*)		func_build_prepare_source_remote_hg "$@" ;;
+		*/git/*)	func_build_prepare_source_remote_git "$@" ;;
+		*)		echo "ERROR: unable to handle build address: $*" ;;
+	esac
+}
+
+function func_build_prepare_source_remote_hg {
+	func_param_check 2 "Usage: $FUNCNAME <source_base> <remote_addr>" "$@" 
+
+	source_base_name=$(basename ${1})
+	source_base_remote=$MY_CODE_MISC/"${source_base_name##*_}"_-HG-
+
+	mkdir -p $MY_CODE_MISC
+	[ -e "$source_base_remote" ] && hg pull && hg update || hg clone "$2" "$source_base_remote"
+	rm -rf "$1" ; ln -s "$source_base_remote" "$1"
+}
+
+function func_build_prepare_source_remote_git {
+	func_param_check 1 "Usage: $FUNCNAME <remote_addr>" "$@" 
+
+	source_base_name=$(basename ${1})
+	source_base_remote=$MY_CODE_MISC/"${source_base_name##*_}"_-GIT-
+
+	mkdir -p $MY_CODE_MISC
+	[ -e "$source_base_remote" ] && git pull || git clone "$2" "$source_base_remote"
+	rm -rf "$1" ; ln -s "$source_base_remote" "$1"
+}
+
+function func_build_prepare_source_remote_download {
+	func_param_check 1 "Usage: $FUNCNAME <remote_addr>" "$@" 
+	echo "ERROR: not implement yet"
+}
+
+function func_build_prepare_source_local {
+	func_param_check 1 "Usage: $FUNCNAME <local_addr>" "$@" 
+	echo "ERROR: not implement yet"
 }
