script for collecting codes

diff --git a/.myenv/env_func_bash b/.myenv/env_func_bash
--- a/.myenv/env_func_bash
+++ b/.myenv/env_func_bash
@@ -73,8 +73,19 @@ function func_validate_cmd_exist() {
 	( ! command -v "$1" &> /dev/null) && echo "ERROR: $1 not found (in PATH)" && exit 1
 }
 
+function func_validate_filetype_text() {
+	func_param_check 1 "USAGE: $FUNCNAME <file>" "$@"
+
+	# TODO: effeciency need improve!
+
+	real_file=$(eval echo "$*")
+	file "$real_file" | grep -q text
+}
+
 function func_cleanup_dotcache() {
 	func_param_check 1 "USAGE: $FUNCNAME <path> ..." "$@"
+
+	#TODO: also cleanup dir above it?
 
 	for p in "$@" ; do
 		[ -e "$p/$DOT_CACHE_DL" ] && rm "$p/$DOT_CACHE_DL" 
@@ -479,6 +490,111 @@ function func_gen_list_f_me {
 	done
 }
 
+function deprecated_func_gen_grep_pattern_str {
+	# Deprecated: passing array between functions is painful!
+	
+	func_param_check 2 "Usage: $FUNCNAME [result_var_name] [patterns]" "$@"
+
+	# need use variable to "return" result
+	result_var_name="$1"
+	eval $result_var_name=""
+	shift
+	patterns=$*
+
+	result_pattern_str='\\\('
+	for pattern in ${patterns[@]}
+	do
+		#pattern=${pattern/./\\\\.}'\\\|'
+		result_pattern_str=${result_pattern_str}${pattern}
+	done
+	result_pattern_str=${result_pattern_str%%\\\\\\\|}'\\\)'
+
+	eval $result_var_name=$result_pattern_str
+}
+
+function func_gen_collection {
+	func_param_check 5 "Usage: $FUNCNAME [target_base] [source_bases] [source_quick_link] [include_patterns] [exclude_patterns]" "$@"
+
+	# TODO: migration: update name func_gen_collection_note
+	# TODO: migration: update name of "collection_quick_link_files"
+	# TODO: migration: update file path in vimrc and xkeybindings
+	# TODO: make it optional: backup original file feature
+
+	target_base="$1"
+	source_bases=$2
+	source_quick_link=$3
+	include_patterns=$4
+	exclude_patterns=$5
+	target_collection_fl=$target_base/collection_fl.txt
+	target_collection_content=$target_base/collection_content.txt
+	target_original_files=/tmp/original_files_$(basename $target_base)
+
+	# clean up old things
+	[ -e "$target_base" ] && rm -rf "$target_base"
+
+	# create patterns for grep cmd
+	include_pattern_str=$(echo ${include_patterns[@]} | sed -e "s/\s/\|/g")
+	exclude_pattern_str=$(echo ${exclude_patterns[@]} | sed -e "s/\s/\|/g")
+
+	# init target dir, gen file lists
+	func_mkdir_cd "$target_base"
+	for tag in ${source_bases[@]}
+	do
+		func_gen_filedirlist $tag $target_base/fl_${tag}.txt -type f
+		#echo "$include_pattern_str"
+		#echo "$exclude_pattern_str"
+		egrep -i "$include_pattern_str" fl_${tag}.txt | egrep -v "$exclude_pattern_str" >> ${target_collection_fl}
+	done
+
+	echo "INFO: start to Collect and backup original file"
+	mkdir $target_original_files
+	[ -n "$source_quick_link" ] && sed -e "" "$source_quick_link" >> ${target_collection_content}
+
+	count=0
+	while read line
+	do
+		source_path="$(func_eval "$line")"
+		[ -d "$source_path" ] && echo -e "INFO: skipping dir: $line" && continue
+
+		# backup original files, need udpate file name to avoid name confliction
+		target_file=$(echo "$line" | sed -e 's+/\|:+@+g;s+\$\| \|\(\|\)\|（\|）\|&++g')
+		cp "$source_path" "$target_original_files/$target_file" 
+
+		# won't collect non-text file
+		func_validate_filetype_text "$line" || continue
+
+		# Collect files
+		#if [ -z "${line##*.txt}" ] ; then 
+			echo -e "\n\n>>> $line\n\n"	>> ${target_collection_content}
+			sed -e "s///" "$source_path"	>> ${target_collection_content}
+		#fi
+		
+		count=$(($count + 1)) && [ $(($count % 100)) -eq 0 ] && echo "INFO: collected $count files"
+	done < ${target_collection_fl}
+
+	# append all file list in the end
+	echo -e "\n\n>>> File list of ${source_bases[@]} \n\n" >> ${target_collection_content}
+	cat fl_*.txt >> ${target_collection_content}
+
+	# backup collection
+	func_backup_dated "$target_original_files" 
+	rm -rf "$target_original_files"
+
+	func_cleanup_dotcache $MY_ENV $MY_ENV_ZGEN
+	\cd - > /dev/null
+}
+
+function func_gen_collection_code {
+	target_base=$MY_ENV/zgen/collection_code
+	source_bases=(dw repo)
+
+	# Note, used "ERE (Extended Regex) to avoid passing "\" around)
+	include_patterns=(.bat$ .sh$ .csh$ .groovy$ .cpp$ .c$ .py$ .rb$ .ruby$ .java$ .html$ .htm$ .js$ .css$ pom.xml$ .php$ .ps$ .md$ .markdown$)
+	exclude_patterns=(.doc$ .min.js$ jquery[-.a-zA-Z0-9]*.[jc]ss?$ bootstrap[-.a-zA-Z0-9]*.[jc]ss?$)	
+
+	func_gen_collection $target_base $source_bases "" $include_patterns $exclude_patterns
+}
+
 function func_gen_collection_note {
 	target_base=$MY_ENV/zgen/collection_note
 	target_original_file=$target_base/original_files
@@ -486,6 +602,21 @@ function func_gen_collection_note {
 	target_note_collection_txt=$target_base/note_collection_txt.txt
 	source_bases=(dcd dco dcc dcb   me   ecb ece ech ecs ecz)	# Not included DCM, put DCD first
 	source_note_list=$MY_ENV/list/collection_quick_link_files
+
+
+
+	target_base=$MY_ENV/zgen/collection_note
+	source_bases=(dcd dco dcc dcb   me   ecb ece ech ecs ecz)	# Not included DCM, put DCD first
+
+	# Note, used "ERE (Extended Regex) to avoid passing "\" around)
+	include_patterns=(A_NOTE_ --NOTE-- --NOTED-- .bash$ .sh$)
+	include_patterns=(.lnk$ /DCB/DatedBackup/)
+	source_quick_link="$MYENV/list/collection_note_quick_link"
+	#func_gen_collection $target_base $source_bases "" $include_patterns $exclude_patterns
+	#return
+
+
+
 
 	# clean up old things
 	[ -e "$target_base" ] && rm -rf "$target_base"
